footprint: [[-0.156, -0.1938], [-0.156, 0.152], [0.156, 0.152], [0.156, -0.1938]]
footprint_padding: 0.1
robot_base_frame: base_link

update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5
resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: scan
    publish_voxel_map:    true
    track_unknown_space:  true
    laser_scan: {data_type: LaserScan, sensor_frame: laser, clearing: true, marking: true, topic: scan, inf_is_valid: false}

inflation:
    inflation_radius: 0.4
    cost_scaling_factor: 4.0