global_costmap:
  update_frequency: 1.0
  transform_tolerance: 0.5
  rolling_window: false
  track_unknown_space: true

  plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: obstacles_laser,         type: "costmap_2d::VoxelLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}